name: C++ LULESH CI
on:
  pull_request:
  push:
jobs:
  build:
    name: C++ LULESH
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    timeout-minutes: 240
    steps:
      - name: package
        run: |
          sudo apt-get install -y autoconf cmake gcc g++ gfortran ninja-build libopenmpi-dev
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: setup cymbl
        run: |
          sudo wget --no-verbose https://github.com/cymbl/cymbl.github.io/releases/download/0.0.1/LLVM-11.0.0git-Linux.sh
          printf "y\nn\n" | sudo bash LLVM-11.0.0git-Linux.sh
          printf "{\"refreshToken\":\"%s\"}" "${{ secrets.SUPERSECRET }}" > ~/.cymblconfig

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: llvm-project/build
          key: ${{ hashFiles('.git/modules/llvm-project/HEAD') }}

      - name: LLVM build
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          cd llvm-project
          mkdir build
          cd build
          CYMBL=OFF cmake ../llvm -GNinja -DLLVM_ENABLE_PROJECTS="llvm;clang;openmp" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_C_COMPILER=${{ github.workspace }}/bin/clang -DCMAKE_CXX_COMPILER=${{ github.workspace }}/bin/clang++ -DCMAKE_ASM_COMPILER=${{ github.workspace }}/bin/clang -DCMAKE_CXX_FLAGS="-Wno-c++11-narrowing"
          ${{ github.workspace }}/bin/cymbld & disown
          sleep 10
          CYMBL=OFF ninja -j125

      - name: Enzyme build
        run: |
          cd Enzyme/enzyme
          mkdir build
          cd build
          CYMBL=OFF cmake .. -GNinja -DLLVM_DIR=${{ github.workspace }}/llvm-project/build -DCMAKE_BUILD_TYPE=Release
          CYMBL=OFF ninja

      - name: build
        env:
          CLANG_PATH: ${{ github.workspace }}/llvm-project/build/bin
          ENZYME_PATH: ${{ github.workspace }}/Enzyme/enzyme/build/Enzyme/ClangEnzyme-15.so
        run: |
          cd LULESH-CPP
          make -j

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: luleshcpp
          path: LULESH-CPP
 
      - run: LULESH-CPP/ser-single-forward.exe -s 10
      - run: LULESH-CPP/ser-single-gradient.exe -s 10
      - run: LULESH-CPP/omp-single-forward.exe -s 10
      - run: LULESH-CPP/omp-single-gradient.exe -s 10
      - run: LULESH-CPP/ompM-single-forward.exe -s 10
      - run: LULESH-CPP/ompM-single-gradient.exe -s 10
      - run: LULESH-CPP/ompOpt-single-forward.exe -s 10
      - run: LULESH-CPP/ompOpt-single-gradient.exe -s 10
      
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/ser-mpi-forward.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/ser-mpi-gradient.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/omp-mpi-forward.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/omp-mpi-gradient.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/ompM-mpi-forward.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/ompM-mpi-gradient.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/ompOpt-mpi-forward.exe -s 10
      - run: mpirun -n 8 --oversubscribe LULESH-CPP/ompOpt-mpi-gradient.exe -s 10
